# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HHContactsManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'JQFMDB'
  # Pods for HHContactsManager

  target 'HHContactsManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HHContactsManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
